version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - OPENWEATHER_API_KEY=7d7a75ab1892413dcbe67b2614ea7649
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:3000/graphql
